PEP8:
  stage: test
  only:
    - merge_requests
  image: python:3.9
  script:
    - pip3 install flake8==5.*
    - git diff -U0 $CI_MERGE_REQUEST_DIFF_BASE_SHA...HEAD | flake8 --diff --max-line-length 120

CHANGELOG:
  stage: test
  only:
    - merge_requests
  script:
    - if ! git diff --name-only $CI_MERGE_REQUEST_DIFF_BASE_SHA...HEAD | grep -q ^CHANGELOG$; then exit 1; fi

pytest:
  stage: test
  image:
    name: gitlab.euclid-sgs.uk:4567/pf-she/she_containers/she_ppt:9.6.1
    entrypoint: [ '/bin/sh', '-c' ]
  variables:
    ELEMENTS_AUX_PATH: /usr/share/auxdir
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_EXPLICIT_VERSION=3 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE ..
    - make install
    - pytest ../SHE_CTE/tests/python
    - pytest ../SHE_CTE_PipelineUtility/tests/python
    - pytest ../SHE_CTE_ShearValidation/tests/python

