pytest:
  stage: test
  image:
    name: gitlab.euclid-sgs.uk:4567/pf-she/she_containers/she_ppt:9.3.1
    entrypoint: [ '/bin/sh', '-c' ]
  variables:
    ELEMENTS_AUX_PATH: /usr/share/auxdir
  script:
    - mkdir build
    - cd build
    - cmake -DPYTHON_EXPLICIT_VERSION=3 -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE ..
    - make install
    - pytest ../SHE_CTE/tests/python
    - pytest ../SHE_CTE_BiasMeasurement/tests/python
    - pytest ../SHE_CTE_PipelineUtility/tests/python
    - pytest ../SHE_CTE_ShearReconciliation/tests/python
    - pytest ../SHE_CTE_ShearValidation/tests/python
